(function () {
    "use strict";

    var _themes = {
            'Herschel': {
                file: 'herschel.css',
                image: 'background-herschel.png',
                copyright: 'Background image generated by <a href="http://rzurad.github.io/TEXTp" target="_new">TEXTp</a> using an image courtesy of the ESA/NASA/Herschel/PACS/MESS Key Programme Supernova Remnant Team/Allison Loll and Jeff Hester (Arizona State University)'

            },
            'Carina': {
                file: 'carina.css',
                image: 'background-carina.png',
                copyright: 'Background image generated by <a href="http://rzurad.github.io/TEXTp" target="_new">TEXTp</a> using an image courtesy of NASA/ESA/M. Livio/The Hubble Heritage Team/Hubble 20th Anniversary Team (STScI)'
            },
            'Helios': {
                file: 'helios.css',
                image: 'background-helios.png',
                copyright: 'Background image generated by <a href="http://rzurad.github.io/TEXTp" target="_new">TEXTp</a> using an image courtesy of NASA/SDO'
            }
        };

    function loadTheme(key) {
        if (key === 'Random' || !(key in _themes)) {
            key = (function (a) {
                return a[~~(Math.random() * a.length)];
            }(Object.keys(_themes)));
        }

        var $head = $('head'),
            theme = _themes[key],
            $oldTheme = $head.find('link[data-theme]');

        $('.image-credits').html(theme.copyright);
        $head.append('<link rel="stylesheet" data-theme="' + key  + '" href="./css/' + theme.file + '">');
        $oldTheme.remove();
    }

    // determine the theme to display:
    //    Use the theme given by a querystring, if it's valid.
    //    Otherwise, use the theme they last selected (if any),
    //    Otherwise, use Herschel
    var qs = window.location.search.match(/theme=([a-zA-Z]+)/),
        ls = localStorage.getItem('theme'),
        $list = $('#theme-list'),
        initialTheme;

    if (qs) {
        qs = qs.pop();

        if (!(qs in _themes) && qs !== 'Random') {
            qs = null;
        }
    }

    initialTheme = qs || ls || 'Random';

    loadTheme(initialTheme);

    // draw the theme list
    Object.keys(_themes).concat(['Random']).forEach(function (key) {
        var active = key === initialTheme ? ' class="active"' : '';

        $list.append(
            '<a href="#" data-theme="' + key + '"' + active + '>' + key + '</a> '
        );
    });

    // bind theme selection click
    $list.on('click', 'a', function (e) {
        var $target = $(e.target),
            key = $target.attr('data-theme');

        e.preventDefault();

        if ($target.is('.active')) {
            return;
        }

        // swap active class
        $target.siblings('.active').removeClass('active');
        $target.addClass('active');

        window.localStorage.setItem('theme', key);
        loadTheme(key);
    });
}());
