(function () {
    "use strict";

    var _themes = {
            'Herschel': {
                file: 'herschel.css',
                copyright: 'Background image generated by <a href="http://rzurad.github.io/TEXTp" target="_new">TEXTp</a> using an image courtesy of the ESA/Herschel/PACS/MESS Key Programme Supernova Remnant Team; NSA, ESA, and Allison Loll/Jeff Hester (Arizona State University)',

            },
            'Carina': {
                file: 'carina.css',
                copyright: 'Background image generated by <a href="http://rzurad.github.io/TEXTp" target="_new">TEXTp</a> using an image courtesy of NASA, ESA, and M. Livio, The Hubble Heritage Team and the Hubble 20th Anniversary Team (STScI)'
            }
        };

    function loadTheme(key) {
        var $head = $('head'),
            theme = _themes[key],
            $oldTheme = $head.find('link[data-theme]');

        $head.append('<link rel="stylesheet" data-theme="' + key  + '" href="./css/' + theme.file + '">');
        $('.image-credits').html(theme.copyright);
        $oldTheme.remove();
    }

    var $list = $('#theme-list');

    // bind theme selection click
    $list.on('click', 'a', function (e) {
        var $target = $(e.target),
            key = $target.attr('data-theme');

        e.preventDefault();

        if ($target.is('.active')) {
            return;
        }

        // swap active class
        $target.siblings('.active').removeClass('active');
        $target.addClass('active');

        loadTheme(key);
    });

    // load a random theme
    /*
    var initialTheme = (function (a) {
        return a[~~(Math.random() * a.length)];
    }(Object.keys(_themes)));
    */
    var initialTheme = 'Herschel';

    loadTheme(initialTheme);

    // draw the theme list
    Object.keys(_themes).forEach(function (key) {
        var active = key === initialTheme ? ' class="active"' : '';

        $list.append(
            '<a href="#" data-theme="' + key + '"' + active + '>' + key + '</a> '
        );
    });
}());
